spring:
  data:
    mongodb:
      uri: mongodb://admin:secret@localhost:27017/bookflux?authSource=admin
      auto-index-creation: true


google:
  books:
    api:
      url: https://www.googleapis.com/books/v1/volumes?q=